### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Arcanaut** [collin-beisel-tm/game-grab#5]
Need to make a search bar (to be placed directly below the header)

**Comment by collin-beisel-tm** [comment]
Brenden & collin to tackle this.

**Comment by collin-beisel-tm** [comment]
Created search functionality. Need to work on the following bugs:

- create an if statement to notify the user when there are no matches to their search
- Figure out why the dynamic parent div (row-container) is not being cleared on subsequent searches
- Fix styling issues that arise with single card layout

**Comment by collin-beisel-tm** [comment]
completed search functionality. 
added if statement that notify's users when there is no match for their search
fixed background color height issue
