### ISSUE TITLE
container with game deals

### ISSUE THREAD

**Issue by Arcanaut** [collin-beisel-tm/game-grab#7]
The container with game deals (in order of best) should have a range of 60 games.

**Comment by collin-beisel-tm** [comment]
i've pulled in the game data to create some basic cards, now i'm trying to modify my for loop to include 4 game cards in each row.

**Comment by collin-beisel-tm** [comment]
Initial api integration and dynamic HTML creation done by Collin. Bulma/JS updates for layout formatting completed by Bo.
